openapi: 3.0.3
info:
  title: Contact API
  version: 1.0.0
paths:
  /v1/contacts:
    post:
      tags:
        - Contacts V1
      summary: Create a new contact
      operationId: createContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContactRequest'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateContactResponse'
          description: Contact created successfully
    get:
      tags:
        - Contacts V1
      summary: Get all contacts
      operationId: getContacts
      responses:
        '200':
          description: Get all contacts
          content:
            application/json:
              schema:
                type: array
                default: []
                items:
                  $ref: '#/components/schemas/Contact'
              example:
                - name:
                    first: 'Juan'
                    last: 'dela Cruz'
                    suffix: 'Jr.'
                  contactNumberList:
                    - countryCode: '+63'
                      areaCode: '917'
                      subscriberNumber: '123456'

components:
  schemas:
    CreateContactRequest:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        contactNumberList:
          type: array
          default: []
          items:
            $ref: '#/components/schemas/ContactNumber'
      example:
        name:
          first: 'Juan'
          last: 'dela Cruz'
          suffix: 'Jr.'
        contactNumberList:
          - countryCode: '+63'
            areaCode: '917'
            subscriberNumber: '123456'
    CreateContactResponse:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
    Contact:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          $ref: '#/components/schemas/Name'
        contactNumberList:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/ContactNumber'
    Name:
      type: object
      properties:
        first:
          type: string
        last:
          type: string
        suffix:
          type: string
      example:
        first: 'Juan'
        last: 'dela Cruz'
        suffix: 'Jr.'
    ContactNumber:
      type: object
      properties:
        countryCode:
          type: string
        areaCode:
          type: string
        subscriberNumber:
          type: string
      example:
        countryCode: '+63'
        areaCode: '917'
        subscriberNumber: '123456'